package com.place.helper.persistent.entity;

// Generated 2015-12-11 11:42:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EncUrl generated by hbm2java
 */
@Entity
@Table(name = "enc_url", catalog = "weibopage")
public class EncUrl implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private PlacePage placePage;
	private String encUrl;

	public EncUrl() {
	}

	public EncUrl(PlacePage placePage, String encUrl) {
		this.placePage = placePage;
		this.encUrl = encUrl;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "place_page_id")
	public PlacePage getPlacePage() {
		return this.placePage;
	}

	public void setPlacePage(PlacePage placePage) {
		this.placePage = placePage;
	}

	@Column(name = "encUrl", length = 64)
	public String getEncUrl() {
		return this.encUrl;
	}

	public void setEncUrl(String encUrl) {
		this.encUrl = encUrl;
	}

}
