package com.place.helper.persistent.entity;

// Generated 2016-1-21 12:57:36 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PlacePoiid generated by hbm2java
 */
@Entity
@Table(name = "place_poiid", catalog = "weibopage")
public class PlacePoiid implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6378492951877623596L;
	private Integer id;
	private PlacePois placePois;
	private String poiId;
	private String placeName;
	private String country;
	private String province;
	private String city;
	private String county;
	private String lat;
	private String lon;

	public PlacePoiid() {
	}

	public PlacePoiid(PlacePois placePois, String poiId, String placeName,
			String country, String province, String city, String county,
			String lat, String lon) {
		this.placePois = placePois;
		this.poiId = poiId;
		this.placeName = placeName;
		this.country = country;
		this.province = province;
		this.city = city;
		this.county = county;
		this.lat = lat;
		this.lon = lon;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "poisId")
	public PlacePois getPlacePois() {
		return this.placePois;
	}

	public void setPlacePois(PlacePois placePois) {
		this.placePois = placePois;
	}

	@Column(name = "poiId", length = 256)
	public String getPoiId() {
		return this.poiId;
	}

	public void setPoiId(String poiId) {
		this.poiId = poiId;
	}

	@Column(name = "placeName", length = 128)
	public String getPlaceName() {
		return this.placeName;
	}

	public void setPlaceName(String placeName) {
		this.placeName = placeName;
	}

	@Column(name = "country", length = 64)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "province", length = 64)
	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	@Column(name = "city", length = 64)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "county", length = 64)
	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	@Column(name = "lat", length = 64)
	public String getLat() {
		return this.lat;
	}

	public void setLat(String lat) {
		this.lat = lat;
	}

	@Column(name = "lon", length = 64)
	public String getLon() {
		return this.lon;
	}

	public void setLon(String lon) {
		this.lon = lon;
	}

}
