package com.place.helper.persistent.entity;

// Generated 2015-12-28 15:44:13 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PlacePois generated by hbm2java
 */
@Entity
@Table(name = "place_pois", catalog = "weibopage")
public class PlacePois implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8796818125611300534L;
	private Integer id;
	private String placeName;
	private String placePois;
	private Set<PlacePoiid> placePoiids = new HashSet<PlacePoiid>(0);

	public PlacePois() {
	}

	public PlacePois(String placeName, String placePois,
			Set<PlacePoiid> placePoiids) {
		this.placeName = placeName;
		this.placePois = placePois;
		this.placePoiids = placePoiids;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "placeName", length = 64)
	public String getPlaceName() {
		return this.placeName;
	}

	public void setPlaceName(String placeName) {
		this.placeName = placeName;
	}

	@Column(name = "placePois", length = 16777215)
	public String getPlacePois() {
		return this.placePois;
	}

	public void setPlacePois(String placePois) {
		this.placePois = placePois;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "placePois")
	public Set<PlacePoiid> getPlacePoiids() {
		return this.placePoiids;
	}

	public void setPlacePoiids(Set<PlacePoiid> placePoiids) {
		this.placePoiids = placePoiids;
	}

}
